config/routes.rb
Xtunes::Application.routes.draw do
  devise_for :users
  
  resources :songs, :albums, :artists, :genres, :mixtapes
  
  match '/home' => 'home#index'
  match '/buy' => 'songs#buy', :via => 'post'
  match '/purchases' => 'purchases#index'
  
  resources :purchases do
    collection do
      match 'search' => 'purchases#search', :via => [:get, "post"], :as => :search
    end
  end

  root :to => 'home#index'

end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  dob        :date
#  photo      :string(255)
#  bio        :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ActiveRecord::Base
  attr_accessible :name, :dob, :bio, :remote_photo_url
  
  has_and_belongs_to_many :songs
  has_many :albums, :through => :songs
  
  mount_uploader :photo, PikUploader  
  

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :authenticate_user!
  before_filter do 
    unless current_user && current_user.admin?
      flash[:warning] = "You do not have access to the requested page!"
      redirect_to home_path 
    end
  end
  
    def index
      @artists = Artist.order(:name)
    end

    def new
      @artist = Artist.new
    end

    def create
      @artist = Artist.new(params[:artist])

      if @artist.save
        flash[:notice] = "You have added #{@artist.name}!"
        redirect_to artists_path
      else
        render :new
      end
    end

    def show
      @artist = Artist.find(params[:id])
      @albums = []
      @artist.albums.each do |a|
        @albums << a
        @albums = @albums.uniq
      end
    end

    def edit
      @artist = Artist.find(params[:id])
    end

    def update
      @artist = Artist.find(params[:id])

      if @artist.update_attributes(params[:artist])
        flash[:notice] = "You have updated #{@artist.name}!"
        redirect_to artist_path(@artist)
      else
        render :edit
      end
    end

    def destroy
      @artist = Artist.find(params[:id])

      @artist.delete

      redirect_to artists_path
    end

  end

app/views/artists/_form.html.erb
<% if @artist.errors.any? %>
  <h2>Errors</h2>
  <ul>
    <% @artist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= simple_form_for(@artist, :html => {:multipart => true, class: "form-vertical"}) do |f| %>
  <%= f.input :name, :label => "Artist Name" %>
  <%= f.input :dob, :label => "Date of Birth", :start_year => 2000, :end_year => 1950 %>
  <%= f.input :bio, :input_html => { :rows => 3 } %>
  <%= f.input :remote_photo_url, :label => "Enter a URL for a picture of the Artist" %>
  <%= f.input :photo, :label => "or Upload One", :as => :file %>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h2>Edit Artist</h2>

<%= render "form" %>

app/views/artists/index.html.erb
<h2>Artist Index</h2>

<table class="table">


<% @artists.each do |a| %>
  <tr>
  <td><%= image_tag(a.photo, :size => "40x40") if a.photo.present? %></td>
  <td><%= a.name %></td>
  <td>
    <%= link_to "Edit ", edit_artist_path(a) %>|
    <%= link_to " Show ", artist_path(a) %>|
    <%= link_to " Delete", artist_path(a), :method => :delete %>
  </td>
  </tr>
  
<% end %>
</table>

<%= link_to "Add an Artist", new_artist_path, :class=> "btn" %>

app/views/artists/new.html.erb
<h2>New Artist</h2>

<%= render 'form' %>

app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>



<%= image_tag(@artist.photo, :size => "150x150") if @artist.photo.present? %><br/>
Born: <%= @artist.dob %><br/>
Bio: <%= @artist.bio %><br/>
<h5>Songs: </h5>
<% @artist.songs.each do |s| %>
  <%= link_to s.name, song_path(s) %><br>
<% end %>
<h5>Albums: </h5>
<% @albums.each do |a| %>
  <%= link_to a.name, album_path(a) %><br>
<% end %>

<br/>
<%= link_to "Edit ", edit_artist_path(@artist) %>|
<%= link_to " Delete", artist_path(@artist), :method => :delete %>