config/routes.rb
Xtunes::Application.routes.draw do
  devise_for :users
  
  resources :songs, :albums, :artists, :genres, :mixtapes
  
  match '/home' => 'home#index'
  match '/buy' => 'songs#buy', :via => 'post'
  match '/purchases' => 'purchases#index'
  
  resources :purchases do
    collection do
      match 'search' => 'purchases#search', :via => [:get, "post"], :as => :search
    end
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @search = Song.search(params[:q])
    if current_user.try(:admin?) || !current_user || current_user.songs.empty?
      @songs = @search.result
    else
      ids_to_exclude = []
        current_user.songs.each do |x|
          ids_to_exclude <<  x.id
        end
      songs_table = Arel::Table.new(:songs)
      @search = Song.where(songs_table[:id].not_in ids_to_exclude).search(params[:q])
      @songs = @search.result
    end
    @songs = @songs.uniq
    
    @mixtapes = Mixtape.find_all_by_user_id(current_user)
    
    
    
    if current_user
      @search_your_songs = current_user.songs.search(params[:q])
      @your_songs = @search_your_songs.result
      @your_songs = @your_songs.uniq
    else
      @your_songs = []
    end
    
    gon.playlist = Song.all.sample(3)
  end
  
end

app/views/home/index.html.erb
<% if current_user %>
  <div class="row">
    <div class="span4 offset4">
      <h2>Xtunes Dashboard</h2>
    </div>
  </div>
<div class="row">
<div class="span6">
  <h3>Your Songs</h3>
  <%= search_form_for @search, :url => search_purchases_path, :html=> {:method => :post}, :builder => SimpleForm::FormBuilder do |f| %>
    <div class="field">
      <%= f.label :name_cont, "Search by Name" %>
      <%= f.text_field :name_cont %>
    </div>
  
    <div class="field">
      <%= f.label :genres_name_cont, "Search by Genre" %>
      <%= f.text_field :genres_name_cont %><br/>
    </div>
    <%= f.button :submit, "Search" %>

  <% end %>

  <table class="table">
    <tr>
      <th><%= sort_link @search_your_songs, :name, "Song"%></th>
      <th></th>
    </tr>

  <% @your_songs.each do |s| %>
    <tr>
      <td><%= link_to s.name, song_path(s) %></td>
      <td><%= audio_tag(s.song_file, :controls => true) if s.song_file.present? %></td>
    </tr>
  <% end %>
  </table>
</div>
<div class="span5 offset1">
  <h3>Your mixtapes</h3>
  <table class="table">
    <tr>
      <th>Mixtape</th>
      <th></th>
    </tr>


  <% @mixtapes.each do |m| %>
    <tr>
      <td><%= m.name %></td>
      <td><%= link_to "Edit ", edit_mixtape_path(m) %>|
      <%= link_to " Show", mixtape_path(m) %>|
      <%= link_to " Delete", mixtape_path(m), :method => :delete %></td>
    </tr>
  <% end %>
  </table>
  <%= link_to "Add a Mixtape", new_mixtape_path, :class=> "btn" %><br/><br/>
  <hr noshade size=3>

  <h3>Add a Song</h3>
  <%= search_form_for @search, :builder => SimpleForm::FormBuilder do |f| %>
    <div class="field">
      <%= f.label :name_cont, "Search by Name" %>
      <%= f.text_field :name_cont %><br/>
    </div>
  
    <div class="field">
      <%= f.label :genres_name_cont, "Search by Genre" %>
      <%= f.text_field :genres_name_cont %><br/>
      <%= f.button :submit, "Search" %>
    </div>

  <% end %>

  <br/>

</div>
</div>
<% else %>
  <div id="greeting">
    <h1>Find and Play songs from your favorite</h1>
    <h1>Xtunes Artists</h1>
  <%= search_form_for @search, :builder => SimpleForm::FormBuilder do |f| %>
    <div class="songsearch">
      <%= f.text_field :name_cont, :placeholder => "Song Name" %>
      <%= f.button :submit, "Search" %>
    </div>
  <% end %>
  </div>
  
  <hr>
  
  <div class="row" id="bottomgreeting">
    <div class="span4 offset1" id="mixtape">
      <h3>Create your own custom Mixtapes</h3>
      <%= link_to "Signup Today", new_user_registration_path, :class=> "btn btn-large btn-warning" %><br/><br/>
    </div>
    <div class="span5 offset1">
      <%= render "layouts/player" %>
      <br/>
    <div>
    
    </div>
  </div>
<% end %>