config/routes.rb
Xtunes::Application.routes.draw do
  devise_for :users
  
  resources :songs, :albums, :artists, :genres, :mixtapes
  
  match '/home' => 'home#index'
  match '/buy' => 'songs#buy', :via => 'post'
  match '/purchases' => 'purchases#index'
  
  resources :purchases do
    collection do
      match 'search' => 'purchases#search', :via => [:get, "post"], :as => :search
    end
  end

  root :to => 'home#index'

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  photo        :string(255)
#  release_date :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Album < ActiveRecord::Base
  attr_accessible :name, :photo, :release_date, :remote_photo_url
  
  has_and_belongs_to_many :songs
  has_many :artists, :through => :songs
  
  mount_uploader :photo, PikUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!
  before_filter do 
    unless current_user && current_user.admin?
      flash[:warning] = "You do not have access to the requested page!"
      redirect_to home_path 
    end
  end
  
    def index
      @albums = Album.order(:name)
    end

    def new
      @album = Album.new
    end

    def create
      @album = Album.new(params[:album])

      if @album.save
        flash[:notice] = "You have added #{@album.name}!"
        redirect_to albums_path
      else
        render :new
      end
    end

    def show
      @album = Album.find(params[:id])
      @artists = []
      @album.artists.each do |a|
        @artists << a
        @artists = @artists.uniq
      end
    end

    def edit
      @album = Album.find(params[:id])
    end

    def update
      @album = Album.find(params[:id])

      if @album.update_attributes(params[:album])
        flash[:notice] = "You have updated #{@album.name}!"
        redirect_to album_path(@album)
      else
        render :edit
      end
    end

    def destroy
      @album = Album.find(params[:id])

      @album.delete

      redirect_to albums_path
    end

  end

app/views/albums/_form.html.erb
<% if @album.errors.any? %>
  <h2>Errors</h2>
  <ul>
    <% @album.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= simple_form_for(@album, :html => {:multipart => true, class: "form-vertical"}) do |f| %>
  <%= f.input :name, :label => "Album Name" %>
  <%= f.input :remote_photo_url, :label => "Enter a URL for the Album Cover" %>
  <%= f.input :photo, :label => "or Upload One", :as => :file %>
  <%= f.input :release_date, :start_year => Time.now.year, :end_year => 1950 %>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
  

app/views/albums/edit.html.erb
<h2>Edit Album</h2>

<%= render "form" %>

app/views/albums/index.html.erb
<h2>Album Index</h2>

<table class="table">

<% @albums.each do |a| %>
  <tr>
  <td><%= image_tag(a.photo, :size => "40x40") if a.photo.present? %></td>
    <td><%= link_to a.name, album_path(a) %></td>
    <td>
      <%= link_to "Edit ", edit_album_path(a) %>|
      <%= link_to " Show ", album_path(a) %>|
      <%= link_to " Delete", album_path(a), :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<%= link_to "Add an Album", new_album_path, :class=> "btn" %>

app/views/albums/new.html.erb
<h2>New Album</h2>

<%= render "form" %>

app/views/albums/show.html.erb
<h2><%= @album.name %></h2>

Release Date: <%= @album.release_date.strftime("%B %d, %Y") %><br/><br/>

<%= image_tag(@album.photo, :size => "150x150") if @album.photo.present? %><br/>
 
<h5>Songs: </h5>
<% @album.songs.each do |s| %>
  <%= link_to s.name, song_path(s) %><br>
<% end %>

<h5>Artists: </h5>
<% @artists.each do |a| %>
  <%= link_to a.name, artist_path(a) %><br>
<% end %>


<br/>
<%= link_to "Edit ", edit_album_path(@album) %>|
<%= link_to " Delete", album_path(@album), :method => :delete %>