config/routes.rb
Xtunes::Application.routes.draw do
  devise_for :users
  
  resources :songs, :albums, :artists, :genres, :mixtapes
  
  match '/home' => 'home#index'
  match '/buy' => 'songs#buy', :via => 'post'
  match '/purchases' => 'purchases#index'
  
  resources :purchases do
    collection do
      match 'search' => 'purchases#search', :via => [:get, "post"], :as => :search
    end
  end

  root :to => 'home#index'

end

app/views/layouts/_player.html.erb
<div id="jquery_jplayer_1" class="jp-jplayer"></div>
  <div id="jp_container_1" class="jp-audio">
  <div class="jp-playlist">
        <ul><li></li></ul>
      </div>
    <div class="jp-type-single">
      <div class="jp-gui jp-interface">
        <ul class="jp-controls">
          <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
          <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
          <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
          <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
          <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
          <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
        </ul>
        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>
        <div class="jp-volume-bar">
          <div class="jp-volume-bar-value"></div>
        </div>
        <div class="jp-time-holder">
          <div class="jp-current-time"></div>
          <div class="jp-duration"></div>
          <ul class="jp-toggles">
            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
          </ul>
        </div>
      </div>
      <div class="jp-title">
        <ul>
          <li>Bubble</li>
        </ul>
      </div>
      <div class="jp-no-solution">
        <span>Update Required</span>
        To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xtunes</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="navbar">
    <div class="navbar-inner">
      <%= link_to "Xtunes", root_path, :class => "brand" %>
      <ul class="nav">
        <li><%= link_to "Buy a Song", songs_path %></li>
        <li><%= link_to "Mixtapes", mixtapes_path %></li>
        <% if current_user %>
          <li><%= link_to "My Songs", purchases_path %></li>
        <% end %>
        <% if current_user.try(:admin?) %>
          <li><%= link_to "Albums", albums_path %></li>
          <li><%= link_to "Artist", artists_path %></li>
          <li><%= link_to "Genres", genres_path %></li>
        <% end %>
      </ul>
      </ul>	
			<ul class="nav pull-right">
			  <% if current_user %>
			    <li><%= image_tag(current_user.gravatar_url, :size => "30x30", :class => "img-circle") %></li>
			    <li><%= link_to current_user.name, edit_user_registration_path %></li>
				  
				  <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
			  <% else %>
				  <li><%= link_to "Sign In", new_user_session_path %></li>
				  <li><%= link_to "Sign Up",   new_user_registration_path %></li>
				  
			  <% end %>
			  
			</ul>
    </div>
  </div>
  <% flash.each do |type, message| %>
    <div class="alert <%= flash_class type%>">
	    <button type="button" class="close" data-dismiss="alert">×</button>
		  <%= message %>
	  </div>
  <% end %>
  <%= yield %> 
</div>
</body>
</html>